// export { default as WhyChooseUs, RelatedPost, SharePost, TagButton } from "./WhyChooseUs";
export { default as Brands } from "./Brands";
export { default as Features } from "./Features";
export { default as Hero } from "./Hero";
export { default as Testimonials } from "./Testimonials";
export { default as Video } from "./Video";
export { default as Pricing } from "./Pricing";
export { default as Contact } from "./Contact";
export { default as HowItWorks } from "./HowItWorks";
export { default as FAQs } from "./FAQs";
